import json
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv
from flask import Flask, request, jsonify
from groq import Groq

load_dotenv()

app = Flask(__name__)
_groq = Groq()

LOG_PATH = Path("audit.jsonl")

# Common English function words used for stylometric feature extraction
_FUNCTION_WORDS = {
    'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
    'should', 'may', 'might', 'must', 'shall', 'can', 'to', 'of', 'in',
    'for', 'on', 'with', 'at', 'by', 'from', 'as', 'into', 'through',
    'this', 'that', 'these', 'those', 'it', 'its', 'and', 'but', 'or',
    'nor', 'so', 'yet', 'not', 'no', 'i', 'you', 'he', 'she', 'we', 'they',
}

SYSTEM_PROMPT = """You are an AI content detector. Analyze the provided text and determine whether it was written by a human or generated by an AI language model.

Respond with ONLY a JSON object — no markdown, no explanation outside the object:
{
  "label": "AI-generated" or "Human-written",
  "ai_probability": <float 0.0–1.0 representing the probability the text is AI-generated; 0.0 = certainly human, 1.0 = certainly AI>,
  "reasoning": "<one or two sentences explaining the key signals you observed>"
}"""


# ---------------------------------------------------------------------------
# Audit log (JSON Lines)
# ---------------------------------------------------------------------------

def write_audit_entry(content_id, creator_id, attribution, llm_result, styl_result, scoring):
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "ai_probability": scoring["ai_probability"],
        "uncertainty": scoring["uncertainty"],
        "confidence_band": scoring["confidence_band"],
        "llm_score_raw": llm_result["confidence"],
        "llm_score_cal": scoring["signals"]["llm"],
        "llm_label": llm_result["label"],
        "llm_reasoning": llm_result["reasoning"],
        "styl_score_raw": styl_result["score"],
        "styl_score_cal": scoring["signals"]["stylometry"],
        "styl_features": styl_result["features"],
    }
    with LOG_PATH.open("a") as f:
        f.write(json.dumps(entry) + "\n")


def get_log(limit=20):
    if not LOG_PATH.exists():
        return []
    lines = LOG_PATH.read_text().splitlines()
    entries = [json.loads(line) for line in lines if line.strip()]
    return list(reversed(entries))[:limit]


# ---------------------------------------------------------------------------
# Signal 1: LLM-based classification (Groq)
# ---------------------------------------------------------------------------

def classify_with_llm(text: str) -> dict:
    """
    Signal 1: LLM-based classification via Groq.
    Measures semantic + contextual alignment with learned patterns.

    Returns:
        label      (str)   "AI-generated" | "Human-written"
        confidence (float) raw score — 0.0 = definitely human, 1.0 = definitely AI
        reasoning  (str)   plain-language explanation from the model
    """
    response = _groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    raw = json.loads(response.choices[0].message.content)

    return {
        "label": str(raw["label"]),
        "confidence": float(raw["ai_probability"]),
        "reasoning": str(raw["reasoning"]),
    }


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics
# ---------------------------------------------------------------------------

def compute_stylometric(text: str) -> dict:
    """
    Signal 2: Stylometric heuristics (pure Python, no API).
    Measures lexical, syntactic, and punctuation patterns.

    Exploits (from planning.md):
        AI  — low variance, high regularity
        Human — higher stylistic entropy (variation)

    Returns:
        score    (float) raw 0.0 = human-like variation, 1.0 = AI-like regularity
        features (dict)  raw measurements before aggregation
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r'\b\w+\b', text.lower())

    if len(sentences) < 2 or len(words) < 20:
        # Blind spot noted in planning.md: "fall short on text — not enough signal"
        return {
            "score": 0.5,
            "features": {"note": "insufficient text for reliable stylometric measurement"},
        }

    # --- Raw features ---
    sent_lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    avg_len = sum(sent_lengths) / len(sent_lengths)
    variance = sum((l - avg_len) ** 2 for l in sent_lengths) / len(sent_lengths)

    ttr = len(set(words)) / len(words)

    punct_count = len(re.findall(r'[^\w\s]', text))
    punct_density = punct_count / len(words)

    func_ratio = sum(1 for w in words if w in _FUNCTION_WORDS) / len(words)

    # --- Feature → AI-regularity score (0=human, 1=AI) ---
    #
    # SUGGESTED thresholds (not specified in planning.md):
    #
    # Sentence length variance:
    #   variance < 5  → very uniform → AI score ≈ 1.0
    #   variance > 80 → very varied  → AI score ≈ 0.0
    #   Rationale: empirical NLP research puts typical AI variance at 5–25,
    #   human variance at 30–100+.
    variance_score = max(0.0, min(1.0, 1.0 - variance / 80.0))

    # Type-Token Ratio:
    #   TTR < 0.40 → low diversity → AI score ≈ 1.0
    #   TTR > 0.72 → high diversity → AI score ≈ 0.0
    #   SUGGESTED guard: TTR is unreliable below 80 words — short texts have
    #   high TTR regardless of authorship (planning.md blind spot: "fall short
    #   on text"). Skip TTR on short texts to avoid penalising an accurate LLM.
    if len(words) >= 80:
        ttr_score = max(0.0, min(1.0, (0.72 - ttr) / 0.32))
        raw_score = max(0.0, min(1.0, 0.55 * variance_score + 0.45 * ttr_score))
    else:
        ttr_score = None
        raw_score = variance_score

    return {
        "score": round(raw_score, 4),
        "features": {
            "avg_sentence_length": round(avg_len, 2),
            "sentence_length_variance": round(variance, 2),
            "type_token_ratio": round(ttr, 4),
            "ttr_used": ttr_score is not None,
            "punctuation_density": round(punct_density, 4),
            "function_word_ratio": round(func_ratio, 4),
        },
    }


# ---------------------------------------------------------------------------
# Confidence scoring — combines both signals
# ---------------------------------------------------------------------------

def combine_signals(llm_raw: float, styl_raw: float) -> dict:
    """
    Calibrate each signal then combine into a single confidence score.

    Calibration formulas from planning.md:
        LLM:  cal = 0.7 * raw + 0.15   (compresses range to 0.15–0.85)
        Styl: cal = 0.9 * raw + 0.05   (compresses range to 0.05–0.95)
    Goal: align both signals to the same probability scale to reduce overconfidence.

    SUGGESTED combination choices (not in planning.md):
        Weights — 75% LLM, 25% stylometric (updated from 60/40).
            LLM captures semantic meaning holistically and is harder to spoof;
            stylometric is a fast deterministic signal but easier to game.
            Weight increased after observing stylometric TTR noise dragging
            down confident LLM readings on short AI-generated text.
        Uncertainty — abs(llm_cal - styl_cal), i.e. how much the two signals disagree.
        Confidence bands:
            < 0.15  → "high"     (signals largely agree)
            < 0.30  → "moderate" (some disagreement)
            ≥ 0.30  → "low"      (signals conflict — treat output with caution)
    """
    llm_cal  = round(0.7 * llm_raw  + 0.15, 4)
    styl_cal = round(0.9 * styl_raw + 0.05, 4)

    ai_probability = round(0.75 * llm_cal + 0.25 * styl_cal, 4)
    uncertainty    = round(abs(llm_cal - styl_cal), 4)

    if uncertainty < 0.15:
        confidence_band = "high"
    elif uncertainty < 0.30:
        confidence_band = "moderate"
    else:
        confidence_band = "low"

    return {
        "ai_probability": ai_probability,
        "uncertainty": uncertainty,
        "confidence_band": confidence_band,
        "signals": {
            "llm": llm_cal,
            "stylometry": styl_cal,
        },
    }


# ---------------------------------------------------------------------------
# Transparency label
# ---------------------------------------------------------------------------

def generate_label(ai_probability: float) -> dict:
    """
    Maps a combined confidence score to the correct transparency label variant.
    Label text and descriptions match planning.md exactly.

    SUGGESTED thresholds (planning.md defines the three variants, not the cutoffs):
        ≥ 0.65 → high-confidence AI
        ≤ 0.35 → high-confidence human
        between → uncertain
    Asymmetry is intentional: a false AI accusation harms a creator more than
    a missed detection harms the platform.
    """
    if ai_probability >= 0.65:
        return {
            "label": "Likely AI-generated (high confidence)",
            "description": (
                "Using this text shows patterns of statistical and stylistic "
                "most likely associated with AI-generated text."
            ),
        }
    if ai_probability <= 0.35:
        return {
            "label": "Likely human-written (high confidence)",
            "description": (
                "Using this content shows variations of language and stylistic patterns "
                "consistent with human writing."
            ),
        }
    return {
        "label": "Uncertain — requires review",
        "description": (
            "Using this content shows the signals could not confidently determine "
            "whether this content was AI-generated or human-written based on available signals."
        ),
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json(force=True)
    text = data.get("text", "")
    creator_id = data.get("creator_id")
    content_id = str(uuid.uuid4())

    llm_result   = classify_with_llm(text)
    styl_result  = compute_stylometric(text)
    scoring      = combine_signals(llm_result["confidence"], styl_result["score"])
    label_result = generate_label(scoring["ai_probability"])

    write_audit_entry(content_id, creator_id, label_result["label"], llm_result, styl_result, scoring)

    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "label": label_result["label"],
        "description": label_result["description"],
        "scoring": scoring,
        "signals": {
            "llm": {
                "label": llm_result["label"],
                "confidence": llm_result["confidence"],
                "reasoning": llm_result["reasoning"],
            },
            "stylometry": {
                "score": styl_result["score"],
                "features": styl_result["features"],
            },
        },
    })


@app.route("/log", methods=["GET"])
def log():
    limit = request.args.get("limit", 20, type=int)
    return jsonify({"entries": get_log(limit)})


# ---------------------------------------------------------------------------
# Appeals
# ---------------------------------------------------------------------------

def lookup_submission(content_id: str):
    """Return the original submission audit entry for content_id, or None."""
    if not LOG_PATH.exists():
        return None
    for line in LOG_PATH.read_text().splitlines():
        if not line.strip():
            continue
        entry = json.loads(line)
        # Submission entries have no "type" field; appeal entries have type="appeal"
        if entry.get("content_id") == content_id and "type" not in entry:
            return entry
    return None


def lookup_appeal(content_id: str):
    """Return the most recent appeal entry for content_id, or None."""
    if not LOG_PATH.exists():
        return None
    match = None
    for line in LOG_PATH.read_text().splitlines():
        if not line.strip():
            continue
        entry = json.loads(line)
        if entry.get("type") == "appeal" and entry.get("content_id") == content_id:
            match = entry
    return match


def write_appeal_entry(appeal_id, content_id, creator_id, creator_reasoning, origin):
    entry = {
        "type": "appeal",
        "appeal_id": appeal_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "content_id": content_id,
        "creator_id": creator_id,
        "status": "under_appeal",
        "creator_reasoning": creator_reasoning,
        "origin_attribution": origin.get("attribution"),
        "origin_ai_probability": origin.get("ai_probability"),
        "origin_llm_score_raw": origin.get("llm_score_raw"),
        "origin_styl_score_raw": origin.get("styl_score_raw"),
    }
    with LOG_PATH.open("a") as f:
        f.write(json.dumps(entry) + "\n")
    return entry


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True)
    content_id        = data.get("content_id")
    creator_id        = data.get("creator_id")
    creator_reasoning = data.get("creator_reasoning")

    missing = [f for f, v in [
        ("content_id", content_id),
        ("creator_id", creator_id),
        ("creator_reasoning", creator_reasoning),
    ] if not v]
    if missing:
        return jsonify({"error": f"Missing required fields: {', '.join(missing)}"}), 400

    origin = lookup_submission(content_id)
    if origin is None:
        return jsonify({"error": f"No submission found for content_id: {content_id}"}), 404

    appeal_id = str(uuid.uuid4())
    entry = write_appeal_entry(appeal_id, content_id, creator_id, creator_reasoning, origin)

    return jsonify({
        "appeal_id": appeal_id,
        "content_id": content_id,
        "creator_id": creator_id,
        "status": "under_appeal",
        "timestamp": entry["timestamp"],
        "origin_attribution": entry["origin_attribution"],
        "creator_reasoning": creator_reasoning,
    }), 201


@app.route("/status/<content_id>", methods=["GET"])
def status(content_id):
    submission = lookup_submission(content_id)
    if submission is None:
        return jsonify({"error": f"No submission found for content_id: {content_id}"}), 404

    appeal = lookup_appeal(content_id)

    return jsonify({
        "content_id": content_id,
        "status": "under_appeal" if appeal else "submitted",
        "attribution": submission.get("attribution"),
        "ai_probability": submission.get("ai_probability"),
        "submitted_at": submission.get("timestamp"),
        "appeal": {
            "appeal_id": appeal["appeal_id"],
            "creator_reasoning": appeal["creator_reasoning"],
            "appealed_at": appeal["timestamp"],
        } if appeal else None,
    })


if __name__ == "__main__":
    app.run(debug=True)
