import json
import math
import re
import uuid
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    storage_uri="memory://",
    default_limits=[],
)

@app.errorhandler(429)
def rate_limit_exceeded(e):
    return jsonify({
        "error": "Rate limit exceeded. Please slow down and try again later.",
        "retry_after": e.description,
    }), 429

_groq = Groq()

LOG_PATH  = Path("audit.jsonl")
CERT_PATH = Path("certificates.jsonl")

# Common English function words used for stylometric feature extraction
_FUNCTION_WORDS = {
    'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
    'should', 'may', 'might', 'must', 'shall', 'can', 'to', 'of', 'in',
    'for', 'on', 'with', 'at', 'by', 'from', 'as', 'into', 'through',
    'this', 'that', 'these', 'those', 'it', 'its', 'and', 'but', 'or',
    'nor', 'so', 'yet', 'not', 'no', 'i', 'you', 'he', 'she', 'we', 'they',
}

SYSTEM_PROMPT = """You are an AI content detector. Analyze the provided text and determine whether it was written by a human or generated by an AI language model.

Respond with ONLY a JSON object — no markdown, no explanation outside the object:
{
  "label": "AI-generated" or "Human-written",
  "ai_probability": <float 0.0–1.0 representing the probability the text is AI-generated; 0.0 = certainly human, 1.0 = certainly AI>,
  "reasoning": "<one or two sentences explaining the key signals you observed>"
}"""

IMAGE_SYSTEM_PROMPT = """You are an AI content detector specializing in image descriptions and captions. Analyze the provided image description and determine whether it was written by a human or generated by an AI.

AI-generated image descriptions tend to be systematically comprehensive, enumerate visual elements in an ordered exhaustive way, and use standardized visual vocabulary ("warm lighting", "sharp focus", "the foreground"). Human descriptions focus on personally salient details, use colloquial language, and often reflect subjective or emotional reactions rather than objective enumeration.

Respond with ONLY a JSON object — no markdown, no explanation outside the object:
{
  "label": "AI-generated" or "Human-written",
  "ai_probability": <float 0.0–1.0; 0.0 = certainly human, 1.0 = certainly AI>,
  "reasoning": "<one or two sentences explaining the key signals you observed>"
}"""

# Ensemble weights per content type.
# image_description down-weights stylometry because captions are short and
# structurally constrained regardless of authorship, making TTR and sentence
# variance unreliable signals.
SIGNAL_WEIGHTS = {
    "text":              {"llm": 0.55, "stylometry": 0.25, "predictability": 0.20},
    "image_description": {"llm": 0.70, "stylometry": 0.15, "predictability": 0.15},
}


# ---------------------------------------------------------------------------
# Audit log (JSON Lines)
# ---------------------------------------------------------------------------

def write_audit_entry(content_id, creator_id, attribution, content_type,
                      llm_result, styl_result, pred_result, scoring):
    entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "content_id": content_id,
        "creator_id": creator_id,
        "content_type": content_type,
        "attribution": attribution,
        "ai_probability": scoring["ai_probability"],
        "uncertainty": scoring["uncertainty"],
        "confidence_band": scoring["confidence_band"],
        "llm_score_raw": llm_result["confidence"],
        "llm_score_cal": scoring["signals"]["llm"],
        "llm_label": llm_result["label"],
        "llm_reasoning": llm_result["reasoning"],
        "styl_score_raw": styl_result["score"],
        "styl_score_cal": scoring["signals"]["stylometry"],
        "styl_features": styl_result["features"],
        "pred_score_raw": pred_result["score"],
        "pred_score_cal": scoring["signals"]["predictability"],
        "pred_features": pred_result["features"],
    }
    with LOG_PATH.open("a") as f:
        f.write(json.dumps(entry) + "\n")


def get_log(limit=20):
    if not LOG_PATH.exists():
        return []
    entries = [json.loads(line) for line in LOG_PATH.read_text().splitlines() if line.strip()]

    appealed_ids = {e["content_id"] for e in entries if e.get("type") == "appeal"}

    annotated = []
    for e in entries:
        if "type" not in e:
            e = {**e, "appeal_filed": e["content_id"] in appealed_ids}
        annotated.append(e)

    return list(reversed(annotated))[:limit]


# ---------------------------------------------------------------------------
# Signal 1: LLM-based classification (Groq)
# ---------------------------------------------------------------------------

def classify_with_llm(text: str, content_type: str = "text") -> dict:
    """
    Signal 1: LLM-based classification via Groq.
    Measures semantic + contextual alignment with learned patterns.

    For content_type="image_description", uses IMAGE_SYSTEM_PROMPT, which is
    tuned to how AI and humans describe visual content differently.

    Returns:
        label      (str)   "AI-generated" | "Human-written"
        confidence (float) raw score — 0.0 = definitely human, 1.0 = definitely AI
        reasoning  (str)   plain-language explanation from the model
    """
    prompt = IMAGE_SYSTEM_PROMPT if content_type == "image_description" else SYSTEM_PROMPT
    response = _groq.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    raw = json.loads(response.choices[0].message.content)

    return {
        "label": str(raw["label"]),
        "confidence": float(raw["ai_probability"]),
        "reasoning": str(raw["reasoning"]),
    }


# ---------------------------------------------------------------------------
# Signal 2: Stylometric heuristics
# ---------------------------------------------------------------------------

def compute_stylometric(text: str) -> dict:
    """
    Signal 2: Stylometric heuristics (pure Python, no API).
    Measures lexical, syntactic, and punctuation patterns.

    Exploits (from planning.md):
        AI  — low variance, high regularity
        Human — higher stylistic entropy (variation)

    Returns:
        score    (float) raw 0.0 = human-like variation, 1.0 = AI-like regularity
        features (dict)  raw measurements before aggregation
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r'\b\w+\b', text.lower())

    if len(sentences) < 2 or len(words) < 20:
        return {
            "score": 0.5,
            "features": {"note": "insufficient text for reliable stylometric measurement"},
        }

    # --- Raw features ---
    sent_lengths = [len(re.findall(r'\b\w+\b', s)) for s in sentences]
    avg_len = sum(sent_lengths) / len(sent_lengths)
    variance = sum((l - avg_len) ** 2 for l in sent_lengths) / len(sent_lengths)

    ttr = len(set(words)) / len(words)

    punct_count = len(re.findall(r'[^\w\s]', text))
    punct_density = punct_count / len(words)

    func_ratio = sum(1 for w in words if w in _FUNCTION_WORDS) / len(words)

    # --- Feature → AI-regularity score (0=human, 1=AI) ---
    # Sentence length variance:
    #   variance < 5  → uniform → AI; variance > 80 → varied → human
    variance_score = max(0.0, min(1.0, 1.0 - variance / 80.0))

    # Type-Token Ratio: skip for texts < 80 words (TTR is unreliable on short
    # texts — high TTR regardless of authorship masks the signal).
    if len(words) >= 80:
        ttr_score = max(0.0, min(1.0, (0.72 - ttr) / 0.32))
        raw_score = max(0.0, min(1.0, 0.55 * variance_score + 0.45 * ttr_score))
    else:
        ttr_score = None
        raw_score = variance_score

    return {
        "score": round(raw_score, 4),
        "features": {
            "avg_sentence_length": round(avg_len, 2),
            "sentence_length_variance": round(variance, 2),
            "type_token_ratio": round(ttr, 4),
            "ttr_used": ttr_score is not None,
            "punctuation_density": round(punct_density, 4),
            "function_word_ratio": round(func_ratio, 4),
        },
    }


# ---------------------------------------------------------------------------
# Signal 3: Predictability — phrase repetition + sentence opener diversity
# ---------------------------------------------------------------------------

def compute_predictability(text: str) -> dict:
    """
    Signal 3: Predictability (pure Python, no API).
    Captures formulaic phrasing and structural repetition that stylometric
    (word-level statistics) and the LLM (semantic) do not directly measure.

    Two sub-measures:
      Bigram uniqueness — ratio of distinct adjacent word pairs to total pairs.
        AI text reuses transition phrases ("it is important", "in conclusion");
        human text produces more varied adjacent-word combinations.
      Sentence opener diversity — fraction of sentences that begin with a
        distinct first word. AI tends to cycle through formal openers
        ("The", "This", "In", "It"); human writing varies more idiosyncratically.

    Calibration (suggested — moderate compression similar to stylometric):
        Pred_score_cal = 0.85 * raw + 0.075

    Returns:
        score    (float) 0.0 = diverse/human-like, 1.0 = formulaic/AI-like
        features (dict)  raw measurements
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = re.findall(r'\b\w+\b', text.lower())

    if len(sentences) < 2 or len(words) < 15:
        return {"score": 0.5, "features": {"note": "insufficient text for predictability measurement"}}

    # Bigram uniqueness — phrase-level diversity (distinct from word-level TTR)
    bigrams = list(zip(words, words[1:]))
    unique_bigram_ratio = len(set(bigrams)) / len(bigrams)
    bigram_score = max(0.0, min(1.0, 1.0 - unique_bigram_ratio))

    # Sentence opener diversity
    starters = []
    for s in sentences:
        sw = re.findall(r'\b\w+\b', s.lower())
        if sw:
            starters.append(sw[0])
    starter_diversity = len(set(starters)) / len(starters) if starters else 1.0
    starter_score = max(0.0, min(1.0, 1.0 - starter_diversity))

    raw_score = max(0.0, min(1.0, 0.5 * bigram_score + 0.5 * starter_score))

    return {
        "score": round(raw_score, 4),
        "features": {
            "unique_bigram_ratio": round(unique_bigram_ratio, 4),
            "sentence_starter_diversity": round(starter_diversity, 4),
        },
    }


# ---------------------------------------------------------------------------
# Confidence scoring — ensemble of all three signals
# ---------------------------------------------------------------------------

def combine_signals(llm_raw: float, styl_raw: float,
                    pred_raw: float = 0.5, content_type: str = "text") -> dict:
    """
    Calibrate each signal then combine into a single ensemble confidence score.

    Calibration (compress raw outputs to a shared probability scale):
        LLM:  cal = 0.7  * raw + 0.15   (from planning.md)
        Styl: cal = 0.9  * raw + 0.05   (from planning.md)
        Pred: cal = 0.85 * raw + 0.075  (suggested for Signal 3)

    Weights (see SIGNAL_WEIGHTS — vary by content_type):
        text:              55% LLM + 25% Stylometry + 20% Predictability
        image_description: 70% LLM + 15% Stylometry + 15% Predictability

    Uncertainty: standard deviation of the three calibrated scores.
    More principled than abs(a - b) with 3+ signals — captures spread across
    all three rather than just the largest pairwise gap.

    Confidence bands:
        < 0.15  -> "high"     (signals largely agree)
        < 0.30  -> "moderate" (some disagreement)
        >= 0.30 -> "low"      (signals conflict — treat output with caution)
    """
    llm_cal  = round(0.7  * llm_raw  + 0.15,  4)
    styl_cal = round(0.9  * styl_raw + 0.05,  4)
    pred_cal = round(0.85 * pred_raw + 0.075, 4)

    weights = SIGNAL_WEIGHTS.get(content_type, SIGNAL_WEIGHTS["text"])
    ai_probability = round(
        weights["llm"]            * llm_cal +
        weights["stylometry"]     * styl_cal +
        weights["predictability"] * pred_cal,
        4,
    )

    mean = ai_probability
    variance = sum((s - mean) ** 2 for s in [llm_cal, styl_cal, pred_cal]) / 3
    uncertainty = round(math.sqrt(variance), 4)

    if uncertainty < 0.15:
        confidence_band = "high"
    elif uncertainty < 0.30:
        confidence_band = "moderate"
    else:
        confidence_band = "low"

    return {
        "ai_probability": ai_probability,
        "uncertainty": uncertainty,
        "confidence_band": confidence_band,
        "signals": {
            "llm": llm_cal,
            "stylometry": styl_cal,
            "predictability": pred_cal,
        },
    }


# ---------------------------------------------------------------------------
# Transparency label
# ---------------------------------------------------------------------------

def generate_label(ai_probability: float) -> dict:
    """
    Maps a combined confidence score to the correct transparency label variant.
    Label text and descriptions match planning.md exactly.

    Thresholds (planning.md defines the three variants, not the cutoffs):
        >= 0.65 -> high-confidence AI
        <= 0.35 -> high-confidence human
        between -> uncertain
    Asymmetry is intentional: a false AI accusation harms a creator more than
    a missed detection harms the platform.
    """
    if ai_probability >= 0.65:
        return {
            "label": "Likely AI-generated (high confidence)",
            "description": (
                "Using this text shows patterns of statistical and stylistic "
                "most likely associated with AI-generated text."
            ),
        }
    if ai_probability <= 0.35:
        return {
            "label": "Likely human-written (high confidence)",
            "description": (
                "Using this content shows variations of language and stylistic patterns "
                "consistent with human writing."
            ),
        }
    return {
        "label": "Uncertain — requires review",
        "description": (
            "Using this content shows the signals could not confidently determine "
            "whether this content was AI-generated or human-written based on available signals."
        ),
    }


# ---------------------------------------------------------------------------
# Lookup helpers (shared by appeals, certificates, and status)
# ---------------------------------------------------------------------------

def lookup_submission(content_id: str):
    """Return the original submission audit entry for content_id, or None."""
    if not LOG_PATH.exists():
        return None
    for line in LOG_PATH.read_text().splitlines():
        if not line.strip():
            continue
        entry = json.loads(line)
        if entry.get("content_id") == content_id and "type" not in entry:
            return entry
    return None


def lookup_appeal(content_id: str):
    """Return the most recent appeal entry for content_id, or None."""
    if not LOG_PATH.exists():
        return None
    match = None
    for line in LOG_PATH.read_text().splitlines():
        if not line.strip():
            continue
        entry = json.loads(line)
        if entry.get("type") == "appeal" and entry.get("content_id") == content_id:
            match = entry
    return match


def write_appeal_entry(appeal_id, content_id, creator_id, creator_reasoning, origin):
    entry = {
        "type": "appeal",
        "appeal_id": appeal_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "content_id": content_id,
        "creator_id": creator_id,
        "status": "under_review",
        "creator_reasoning": creator_reasoning,
        "origin_attribution": origin.get("attribution"),
        "origin_ai_probability": origin.get("ai_probability"),
        "origin_llm_score_raw": origin.get("llm_score_raw"),
        "origin_styl_score_raw": origin.get("styl_score_raw"),
    }
    with LOG_PATH.open("a") as f:
        f.write(json.dumps(entry) + "\n")
    return entry


def lookup_certificate(content_id: str):
    """Return the most recent provenance certificate for content_id, or None."""
    if not CERT_PATH.exists():
        return None
    match = None
    for line in CERT_PATH.read_text().splitlines():
        if not line.strip():
            continue
        entry = json.loads(line)
        if entry.get("content_id") == content_id:
            match = entry
    return match


def issue_certificate(content_id: str, creator_id: str, scoring: dict) -> dict:
    cert = {
        "certificate_id": f"cert-{uuid.uuid4().hex[:12]}",
        "content_id": content_id,
        "creator_id": creator_id,
        "issued_at": datetime.now(timezone.utc).isoformat(),
        "ai_probability": scoring["ai_probability"],
        "confidence_band": scoring["confidence_band"],
        "status": "verified_human",
        "badge": "Verified Human-Written",
    }
    with CERT_PATH.open("a") as f:
        f.write(json.dumps(cert) + "\n")
    return cert


# ---------------------------------------------------------------------------
# Routes — submission
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("5 per minute")
@limiter.limit("30 per hour")
@limiter.limit("100 per day")
def submit():
    data = request.get_json(force=True)
    text         = data.get("text", "")
    creator_id   = data.get("creator_id")
    content_type = data.get("content_type", "text")

    if content_type not in SIGNAL_WEIGHTS:
        return jsonify({
            "error": (
                f"Unsupported content_type '{content_type}'. "
                f"Supported types: {list(SIGNAL_WEIGHTS.keys())}"
            )
        }), 400

    content_id = str(uuid.uuid4())

    llm_result  = classify_with_llm(text, content_type)
    styl_result = compute_stylometric(text)
    pred_result = compute_predictability(text)
    scoring     = combine_signals(
        llm_result["confidence"],
        styl_result["score"],
        pred_result["score"],
        content_type,
    )
    label_result = generate_label(scoring["ai_probability"])

    write_audit_entry(
        content_id, creator_id, label_result["label"],
        content_type, llm_result, styl_result, pred_result, scoring,
    )

    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "content_type": content_type,
        "label": label_result["label"],
        "description": label_result["description"],
        "scoring": scoring,
        "signals": {
            "llm": {
                "label": llm_result["label"],
                "confidence": llm_result["confidence"],
                "reasoning": llm_result["reasoning"],
            },
            "stylometry": {
                "score": styl_result["score"],
                "features": styl_result["features"],
            },
            "predictability": {
                "score": pred_result["score"],
                "features": pred_result["features"],
            },
        },
    })


@app.route("/log", methods=["GET"])
def log():
    limit = request.args.get("limit", 20, type=int)
    return jsonify({"entries": get_log(limit)})


# ---------------------------------------------------------------------------
# Routes — appeals
# ---------------------------------------------------------------------------

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True)
    content_id        = data.get("content_id")
    creator_id        = data.get("creator_id")
    creator_reasoning = data.get("creator_reasoning")

    missing = [f for f, v in [
        ("content_id", content_id),
        ("creator_id", creator_id),
        ("creator_reasoning", creator_reasoning),
    ] if not v]
    if missing:
        return jsonify({"error": f"Missing required fields: {', '.join(missing)}"}), 400

    origin = lookup_submission(content_id)
    if origin is None:
        return jsonify({"error": f"No submission found for content_id: {content_id}"}), 404

    appeal_id = str(uuid.uuid4())
    entry = write_appeal_entry(appeal_id, content_id, creator_id, creator_reasoning, origin)

    return jsonify({
        "message": "Appeal received. Your content has been flagged for human review.",
        "appeal_id": appeal_id,
        "content_id": content_id,
        "creator_id": creator_id,
        "status": "under_review",
        "timestamp": entry["timestamp"],
        "original_decision": entry["origin_attribution"],
        "creator_reasoning": creator_reasoning,
    }), 201


@app.route("/status/<content_id>", methods=["GET"])
def status(content_id):
    submission = lookup_submission(content_id)
    if submission is None:
        return jsonify({"error": f"No submission found for content_id: {content_id}"}), 404

    app_entry = lookup_appeal(content_id)

    return jsonify({
        "content_id": content_id,
        "status": app_entry["status"] if app_entry else "submitted",
        "attribution": submission.get("attribution"),
        "ai_probability": submission.get("ai_probability"),
        "submitted_at": submission.get("timestamp"),
        "appeal": {
            "appeal_id": app_entry["appeal_id"],
            "creator_reasoning": app_entry["creator_reasoning"],
            "appealed_at": app_entry["timestamp"],
        } if app_entry else None,
    })


# ---------------------------------------------------------------------------
# Routes — provenance certificates (stretch feature)
# ---------------------------------------------------------------------------

@app.route("/certificate", methods=["POST"])
def certificate():
    """
    Issue a 'Verified Human-Written' provenance certificate.

    Eligibility: the content must have been classified as
    'Likely human-written (high confidence)' (ai_probability <= 0.35).
    If a certificate already exists for this content_id, the existing
    one is returned (idempotent).

    Display: the returned 'badge' field ("Verified Human-Written") is
    intended to be shown on-platform alongside the content. The
    certificate_id serves as a tamper-evident reference — any downstream
    system can call GET /certificate/<content_id> to verify it.
    """
    data = request.get_json(force=True)
    content_id = data.get("content_id")
    creator_id = data.get("creator_id")

    missing = [f for f, v in [("content_id", content_id), ("creator_id", creator_id)] if not v]
    if missing:
        return jsonify({"error": f"Missing required fields: {', '.join(missing)}"}), 400

    submission = lookup_submission(content_id)
    if submission is None:
        return jsonify({"error": f"No submission found for content_id: {content_id}"}), 404

    ai_prob = submission.get("ai_probability", 1.0)
    if ai_prob > 0.35:
        return jsonify({
            "error": (
                "Certificate not issued. Content must be classified as "
                "'Likely human-written (high confidence)' (ai_probability <= 0.35) "
                "to receive a provenance certificate."
            ),
            "ai_probability": ai_prob,
            "attribution": submission.get("attribution"),
        }), 422

    existing = lookup_certificate(content_id)
    if existing:
        return jsonify(existing), 200

    cert = issue_certificate(content_id, creator_id, {
        "ai_probability": submission["ai_probability"],
        "confidence_band": submission["confidence_band"],
    })
    return jsonify(cert), 201


@app.route("/certificate/<content_id>", methods=["GET"])
def get_certificate(content_id):
    """Retrieve a previously issued provenance certificate by content_id."""
    cert = lookup_certificate(content_id)
    if cert is None:
        return jsonify({"error": f"No certificate found for content_id: {content_id}"}), 404
    return jsonify(cert)


# ---------------------------------------------------------------------------
# Routes — analytics dashboard (stretch feature)
# ---------------------------------------------------------------------------

@app.route("/analytics", methods=["GET"])
def analytics():
    """
    Aggregate metrics across all submissions and appeals.

    Metrics:
      total_submissions            - total submission records in audit log
      detection_ratio              - fraction of each label variant
      appeal_rate                  - fraction of submissions that were appealed
      avg_ai_probability           - mean ai_probability across submissions
      avg_uncertainty              - mean uncertainty (signal spread) across submissions
      confidence_band_distribution - fraction in each band (high/moderate/low)
      certificates_issued          - number of provenance certificates issued
    """
    if not LOG_PATH.exists():
        return jsonify({"error": "No data yet"}), 404

    entries = [json.loads(l) for l in LOG_PATH.read_text().splitlines() if l.strip()]
    submissions = [e for e in entries if "type" not in e]
    appeals     = [e for e in entries if e.get("type") == "appeal"]

    if not submissions:
        return jsonify({"error": "No submissions yet"}), 404

    total = len(submissions)
    submitted_ids = {s["content_id"] for s in submissions}
    appealed_content_ids = {
        a["content_id"] for a in appeals if a["content_id"] in submitted_ids
    }

    label_counts = {"ai_high_confidence": 0, "human_high_confidence": 0, "uncertain": 0}
    band_counts  = {"high": 0, "moderate": 0, "low": 0}
    total_ai_prob    = 0.0
    total_uncertainty = 0.0

    for s in submissions:
        attr = s.get("attribution", "")
        if "AI-generated" in attr:
            label_counts["ai_high_confidence"] += 1
        elif "human-written" in attr:
            label_counts["human_high_confidence"] += 1
        else:
            label_counts["uncertain"] += 1

        band = s.get("confidence_band", "")
        if band in band_counts:
            band_counts[band] += 1

        total_ai_prob     += s.get("ai_probability", 0.0)
        total_uncertainty += s.get("uncertainty", 0.0)

    certs = []
    if CERT_PATH.exists():
        certs = [json.loads(l) for l in CERT_PATH.read_text().splitlines() if l.strip()]

    return jsonify({
        "total_submissions": total,
        "detection_ratio": {k: round(v / total, 3) for k, v in label_counts.items()},
        "appeal_rate": round(len(appealed_content_ids) / total, 3),
        "avg_ai_probability": round(total_ai_prob / total, 4),
        "avg_uncertainty": round(total_uncertainty / total, 4),
        "confidence_band_distribution": {k: round(v / total, 3) for k, v in band_counts.items()},
        "certificates_issued": len(certs),
    })


if __name__ == "__main__":
    app.run(debug=True)
